#生产环境配置
server:
  port: 8800
springdoc:
  api-docs:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  mail:
    host: smtp.qq.com
    username: 3340584380@qq.com
    password: nvmcaivqkrhrciaj
    port: 465
    properties:
      from: 3340584380@qq.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:mysql://114.55.246.213:3306/flood?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: GuoYaoYU1.
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 10
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
